services:
  db:
    image: postgres:15
    container_name: gs-db
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: gs-app
    environment:
      SPREADSHEET_ID:                ${SPREADSHEET_ID}
      TABLE_NAME:                    ${TABLE_NAME}
      DATABASE_URL:                  ${DATABASE_URL}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
