version: "3.8"

services:
  importador:
    build: .
    container_name: gs_importer
    env_file:
      - .env
    depends_on:
      - cartagena_superset_db
    networks:
      - superset_net

  cartagena_superset_db:
    image: postgres:14
    container_name: cartagena_superset_db
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: Sup3rs3gura321
      POSTGRES_DB: superset
    ports:
      - "5448:5432"
    networks:
      - superset_net

networks:
  superset_net:
