version: '3.8'
services:
  app:
    build: .
    container_name: gs-app
    env_file: .env
    ports:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: gs-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
